spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ENTER_YOUR_CLIENT_ID
            client-secret: ENTER_YOUR_CLIENT_SECRET
            scope:
              - email
              - profile
