spring:
  devtools:
    remote:
      restart:
        enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sns?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: update
  profiles:
    include: oauth
server:
  servlet:
    context-path: /
    encoding:
      force-response: true
